# These are supported funding model platforms

1. Mohammed Ahmed Majid # Virualizer engineer and software techician, Al Barkaat Public School(+2)
2. Mohammed Yousuf Majid # B.Tech Mechanical Engineering, Aligarh Muslim University
